Initial copy of performance and performance-types to packages-exp
firebase/firebase-js-sdk pull request #3778
Opened 2020-09-15 00:50 UTC by jposuna

There are barely any changes compared to the standard performance package. Only changed the relevant information in the package.json for both folders.

2020-09-15 16:26 UTC, alikn approved these changes

2020-09-15 23:12 UTC, hsubox76 requested changes

2020-09-15 23:12 UTC, hsubox76 commented on packages-exp/performance-exp/CHANGELOG.md
> +# @firebase/performance
Probably don't want to copy this file.

2020-09-15 23:12 UTC, hsubox76 commented on packages-exp/performance-exp/README.md
> +# @firebase/performance
add "-exp"

2020-09-15 23:12 UTC, hsubox76 commented on packages-exp/performance-exp/index.ts
> + * Copyright 2019 Google LLC
Update years in copyright comments, here and elsewhere.

2020-09-15 23:12 UTC, hsubox76 commented on packages-exp/performance-exp/package.json
> +  "version": "0.4.1",
We're setting this to "0.0.800" for all -exp packages.

2020-09-15 23:12 UTC, hsubox76 commented on packages-exp/performance-types-exp/package.json
> +  "version": "0.0.13",
"0.0.800"

2020-09-16 00:41 UTC, hsubox76 approved these changes

2020-09-16 00:41 UTC, hsubox76 commented on packages-exp/performance-exp/rollup.config.js
> + * Copyright 2018 Google LLC
I think this one got missed.

2020-09-16 17:26 UTC, merged