Add a way to specify emulator host/port for Auth
firebase/firebase-js-sdk pull request #3810
Opened 2020-09-18 17:49 UTC by avolkovi

2020-09-21 23:23 UTC, MeghaB approved these changes
lgtm - thanks for adding the console warning!

2020-10-08 19:24 UTC, yuchenshi commented on packages/auth/src/auth.js
> +  if (goog.global.document) {
```suggestion
  if (goog.global.document && goog.global.document.body) {
```

2020-10-13 18:24 UTC, samhorlbeck commented on packages/auth/src/auth.js
> +    const ele = goog.global.document.createElement('p');
This should probably be a `<div>`instead but no need to change it now

2020-10-13 18:28 UTC, samhorlbeck approved these changes

2020-10-13 20:00 UTC, Feiyang1 requested changes
Can you please add the corresponding typings to `packages/firebase/index.d.ts`?

2020-10-13 20:04 UTC, Feiyang1 commented
Actually are you planning to make this API public now, or later?

2020-10-13 21:00 UTC, Feiyang1 commented on packages/firebase/index.d.ts
> +     * @param url - The URL at which the emulator is running (eg, 'http://localhost:9099')
```suggestion
     * @param url The URL at which the emulator is running (eg, 'http://localhost:9099')
```

We are using JSDoc currently, which doesn't requires the `-` after the  parameter name

2020-10-13 21:10 UTC, Feiyang1 approved these changes

2020-10-13 21:30 UTC, merged