Functions: Bind window to passed fetch function
firebase/firebase-js-sdk pull request #3853
Opened 2020-09-28 19:56 UTC by hsubox76

Fix a bug caused by PR https://github.com/firebase/firebase-js-sdk/pull/3782 to replace isomorphic-fetch dependency in functions. Bug occurs in Chrome extensions and possibly other environments. When passing `fetch` function as an argument it loses `window` context.

See https://stackoverflow.com/questions/44720448/fetch-typeerror-failed-to-execute-fetch-on-window-illegal-invocation for a similar issue.

Fixes https://github.com/firebase/firebase-js-sdk/issues/3849

2020-09-30 17:51 UTC, Feiyang1 requested changes
Can you please add changeset?

2020-09-30 18:17 UTC, hsubox76 commented
> Can you please add changeset?

Changeset added!

2020-10-01 03:21 UTC, Feiyang1 commented on .changeset/dirty-rings-cry.md
> +'@firebase/functions-exp': patch
Please remove `@firebase/functions-exp`. Exp packages should not be included in changeset.

2020-10-01 16:47 UTC, Feiyang1 approved these changes

2020-10-01 18:47 UTC, merged

2020-10-07 11:29 UTC, zaripych commented
@hsubox76  +1 for fixing the security issue with `node-fetch` earlier, just a bit of relevant information here that the bug actually used to happen not just in Chrome extensions. I have a CRA app (built with webpack) and was hitting this one. It was a little tricky to diagnose because exception message was hidden in here: 

https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/api/service.ts#L200

I managed to dig-out the error to be `"TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation"`.

Anyway, with new `firebase` package release the issue is fixed. Just a little feedback - it would probably be great if that `e` variable is somehow "converted" to a proper error JSON object so that information is not lost and it's easy to diagnose what is happening. 

Thanks!

2020-10-07 15:50 UTC, hsubox76 commented
Thanks for the additional information that it isn't just Chrome extensions.

As for throwing the error instead of hiding it, I did look into that, but it's tricky. Most of the time, the error that comes from the try/catch around the "fetch" is simply "Failed to fetch" (on Chrome) which will happen if it's a network error, but also if there is an error in the actual Cloud Function code, which would be misleading and cause developers to waste time trying to debug network issues instead of checking the function code.  So when it was originally coded, the decision was made to hide the error because it was potentially more misleading than helpful.

If there was a way to detect and hide "Failed to fetch" errors, we could throw all other errors. However it seems brittle to detect it based on message text, which could change, and the type is TypeError, same as the one we would want to show, above. Additionally, on Firefox the error text is "NetworkError when attempting to fetch resource" and who knows what it is in other browsers.