Fix some incorrect typings / missing pieces in the new auth SDK
firebase/firebase-js-sdk pull request #4187
Opened 2020-12-08 22:25 UTC by samhorlbeck

Specifically, this PR:
  * Fixes the return type of `setPersistence` to be the correct value (`Promise<void>`) in the typings package
  * Adds `OAuthProvider.credentialFromResult()` and `OAuthProvider.credentialFromError()`

2020-12-08 22:28 UTC, samtstern approved these changes

2020-12-09 16:17 UTC, yuchenshi approved these changes

2020-12-09 16:57 UTC, hsubox76 approved these changes

2020-12-09 17:00 UTC, samtstern requested changes
While you're in here making changes can we fix `getAuth()` to require the `app` argument?  According to @Feiyang1 it should be required.

2020-12-09 18:25 UTC, samhorlbeck commented
Okay @samtstern, I've added the fixes for `getAuth()` and `initializeAuth()`

2020-12-09 19:18 UTC, samtstern approved these changes

2020-12-09 20:11 UTC, merged