Fix analytics logEvent public signatures
firebase/firebase-js-sdk pull request #4469
Opened 2021-02-12 20:48 UTC by hsubox76

`eventParams` should be an optional argument.

2021-02-24 00:27 UTC, Feiyang1 requested changes
It should have a changeset.

2021-02-24 17:27 UTC, hsubox76 commented
I added a changeset. By default it only wanted to add the `firebase` package because only `packages/firebase/index.d.ts` changed but I thought `@firebase/analytics` should be added so it goes under "analytics" in the changelog.

2021-02-24 22:28 UTC, Feiyang1 commented
I don't think we should bump `@firebase/analytics` since it has no changes. Is the typing correct in `@firebase/analytics-types`?

2021-02-25 18:23 UTC, Feiyang1 approved these changes

2021-02-25 20:01 UTC, merged