Spli listeners regisration flow for window and sw
firebase/firebase-js-sdk pull request #4672
Opened 2021-03-24 15:38 UTC by zwu52

Specifically:
- index.ts (window entry) registers message listeners
- index.sw.ts registers the onPush, onSubChange, onClick listeners.

Note that some listeners registration requires an instance  of the firebase messaging. Therefore, the listeners registration process needs to be done once firebase sdk registration completes.

2021-03-30 17:58 UTC, Feiyang1 requested changes
The PR seems to also contain changes from https://github.com/firebase/firebase-js-sdk/pull/4665

Do you mean to combine the two? If not, can you rebase this PR, so it only contains registration changes?

2021-03-30 17:58 UTC, Feiyang1 commented on packages-exp/messaging-exp/src/index.sw.ts
> +});
I don't think we want to auto-initialize messaging on user's behalf. It also doesn't work well if user creates multiple app/messaging instances. Can we move the listeners registration to the `getMessaging()` function, so they are registered when developer initializes messaging?

It also means we will have 2 versions of `getMessaging()`, one for the client and one of the sw.

2021-04-02 22:18 UTC, zwu52 reviewed
> The PR seems to also contain changes from #4665
> 
> Do you mean to combine the two? If not, can you rebase this PR, so it only contains registration changes?

not sure how to do it correctly. Tried rebase to the `isSupported` branch and pulled in a bunch of irrelevant files

Can you approve the isSupported PR and I'll rebase from origin

2021-04-08 22:01 UTC, Feiyang1 approved these changes

2021-04-08 22:02 UTC, merged