Combine Firestore and Database API scripts
firebase/firebase-js-sdk pull request #4759
Opened 2021-04-08 19:49 UTC by schmidt-sebastian

2021-04-08 21:39 UTC, schmidt-sebastian commented
Hm, this doesn't seem to work on CI. I will investigate.

2021-04-09 18:17 UTC, Feiyang1 requested changes

2021-04-09 18:17 UTC, Feiyang1 commented on packages/firestore/package.json
> +    "api-report": "run-s api-report:exp api-report:lite api-report:api-json",
```suggestion
    "api-report": "run-s api-report:exp api-report:lite && yarn api-report:api-json",
```

We want to generate API json from the trimmed dts, so we should run it sequentially.

2021-04-09 19:23 UTC, Feiyang1 approved these changes

2021-04-09 22:19 UTC, merged