Add listeners registration to `messaging-compat`
firebase/firebase-js-sdk pull request #4918
Opened 2021-05-17 18:00 UTC by zwu52

`messaging-compat` is a compatibility layer that bridges the v8 and v9(modular) JS API. It's created through wrapping the v9 SDK to recreate the v8 API surface. The objective is to allow developer to gradually migrate to v9 without having to migrate the entire codebase. 

Now the v9 SDK registers its listeners (`onPush`, `onSubChange`, `onMessage`) in `getMessagingInWindow` and `getMessagaingInSw` which is not called in the `messaging-compat`. Without these listeners, the compat SDK can only `getToken` and not get callbacks in `onMessage` and `onBackgroundMessage` 

This PR exports a conditional listeners register from the v9 SDK and calls it in the messaging-compat constructor

2021-05-17 18:50 UTC, Feiyang1 commented on common/api-review/messaging-exp.api.md
> +export function _registerListeners(messaging: FirebaseMessaging): void;
👍

2021-05-17 18:50 UTC, Feiyang1 commented on common/api-review/messaging-exp.api.md
> +export function _registerListeners(messaging: FirebaseMessaging): void;
On second thought, can we register the listeners in the factories, so we don't need to export this special function?

2021-05-19 19:55 UTC, Feiyang1 requested changes
In `@firebase/messaging-compat`, we need to check the environment, and get the correct provider (`messaging-exp` or `messaging-sw-exp`) depending on the environment. 

https://github.com/firebase/firebase-js-sdk/blob/master/packages-exp/messaging-compat/src/registerMessagingCompat.ts#L38

2021-05-19 20:06 UTC, zwu52 commented
right. Good catch!

2021-05-20 20:51 UTC, Feiyang1 reviewed
Sorry! requesting one more change:
let's remove `onBackgroundMessage()` from the main entry point https://github.com/firebase/firebase-js-sdk/blob/master/packages-exp/messaging-exp/src/index.ts#L34,

and remove the `@internal` annotation here - https://github.com/firebase/firebase-js-sdk/blob/master/packages-exp/messaging-exp/src/api.ts#L176

2021-05-20 22:25 UTC, Feiyang1 approved these changes

2021-05-21 00:24 UTC, merged