Mila/count
firebase/firebase-js-sdk pull request #6597
Opened 2022-09-13 21:31 UTC by milaGGL

2022-09-15 18:39 UTC, dconeybe requested changes
Looks great! I had a few ideas that popped up that should have come up in my earlier reviews. PTAL and let me know what you think.

2022-09-15 21:31 UTC, milaGGL commented on .changeset/light-ties-rhyme.md
> +---
changeset check is failing. Added this fie via `yarn changeset add`, but this seems incorrect. 🤔

2022-09-16 18:15 UTC, dconeybe requested changes
Just 2 minor comments then I think we're good!

2022-09-16 18:15 UTC, dconeybe commented on .changeset/hot-insects-wink.md
> +Release count query for internal use.
nit: "Release" -> "Implement"

2022-09-16 18:15 UTC, dconeybe commented on packages/firestore/src/core/firestore_client.ts
> +      const result = await getCount(query);
Lines 529 and 530 still need to be in an "else" block.

2022-09-16 18:50 UTC, dconeybe approved these changes

2022-09-16 19:51 UTC, merged