add 'already-exists' to isRetryableTransactionError
firebase/firebase-js-sdk pull request #6729
Opened 2022-10-26 21:28 UTC by milaGGL

work inprogress

2022-10-27 19:27 UTC, dconeybe requested changes
LGTM. Just two very minor comments!

2022-10-27 19:27 UTC, dconeybe commented on packages/firestore/test/integration/api/transactions.test.ts
> +          // On the first attemp, create a doc before transaction.set(), so that
nit: "attemp" -> "attempt"

2022-10-27 19:27 UTC, dconeybe commented on packages/firestore/test/integration/api/transactions.test.ts
> +      const result = await getDoc(docRef);
nit: Please rename `result` to `snapshot`.

2022-10-27 20:29 UTC, dconeybe approved these changes

2022-10-28 14:18 UTC, tom-andersen approved these changes
Nice

2022-10-28 15:41 UTC, merged