Relaxing in restrictions.
firebase/firebase-js-sdk pull request #6757
Opened 2022-11-04 23:15 UTC by MarkDuckworth

- relaxing in restrictions
- port of https://github.com/firebase/firebase-android-sdk/pull/4231

2022-11-07 23:06 UTC, ehsannas requested changes

2022-11-07 23:06 UTC, ehsannas commented on packages/firestore/test/integration/api/query.test.ts
> +
same thing here

2022-11-09 18:21 UTC, MarkDuckworth commented on packages/firestore/test/integration/api/validation.test.ts
> -
fixed

2022-11-09 18:26 UTC, MarkDuckworth commented on packages/firestore/test/integration/api/query.test.ts
> +
added

2022-11-09 18:26 UTC, MarkDuckworth commented on packages/firestore/test/integration/api/query.test.ts
> +
yikes. Fixed

2022-11-11 00:33 UTC, ehsannas commented on packages/firestore/test/integration/api/validation.test.ts
> +    validationIt.only(
remote `.only`

2022-11-11 00:36 UTC, ehsannas approved these changes

2023-02-09 21:17 UTC, closed without merging

2023-02-09 21:19 UTC, MarkDuckworth commented
Cherry picked to https://github.com/firebase/firebase-js-sdk/pull/7024.