Update firestore docs for typos
firebase/firebase-js-sdk pull request #7173
Opened 2023-03-30 16:20 UTC by dwyfrequency

Necessary for internal cl/520368128 presubmit

2023-03-30 16:35 UTC, markarndt approved these changes

2023-03-30 17:21 UTC, hsubox76 requested changes

2023-03-30 17:21 UTC, hsubox76 commented on packages/auth/api-extractor.json
> +    "mainEntryPointFilePath": "<projectFolder>/dist/esm5/index.doc.d.ts",
Revert this (the script is supposed to do it, not sure why it isn't)

2023-03-30 17:29 UTC, hsubox76 approved these changes

2023-03-31 15:28 UTC, egilmorez approved these changes
Thanks for the follow-up!

2023-03-31 16:06 UTC, sam-gc approved these changes

2023-03-31 16:07 UTC, merged