Update the JSDoc for enableIndexedDbPersistence
firebase/firebase-js-sdk pull request #7852
Opened 2023-12-11 16:52 UTC by milaGGL

In some situations, `enableIndexedDbPersistence` and `enableMultiTabIndexedDbPersistence` throw an error instead of rejecting a promise. Rejected promise is documented as the way the error will be surfaced.
https://github.com/firebase/firebase-js-sdk/blob/03ba26296ef029c844f9fbd6c11e3c773cf8eb14/packages/firestore/test/integration/browser/indexeddb.test.ts#L41

https://github.com/firebase/firebase-js-sdk/blob/03ba26296ef029c844f9fbd6c11e3c773cf8eb14/packages/firestore/test/integration/api/provider.test.ts#L151
Updated the documentation accordingly.

2023-12-12 20:46 UTC, dconeybe requested changes
Looking at the code, I don't think the documentation updates are correct. It appears that both the `enableIndexedDbPersistence()` and `enableMultiTabIndexedDbPersistence()`  functions directly throw exceptions for some problems, and return a promise that is ultimately rejected for other problems.

Specifically, it looks like they throw an exception when misused and return a promise that eventually gets rejected if some problem out of the programmer's control prevents persistence from being set (e.g. indexeddb is not available).

So I'd recommend to revert your changes in this PR, then, just _add_ some information, to indicate that an exception is thrown if persistence has already been enabled or if it is too late to enable persistence. Of course, verify that this is indeed correct. I'm just concerned that the updated documentation is still not fully correct.

2023-12-19 03:09 UTC, dconeybe requested changes
A few minor nits. Please take my comments as suggestions, rather than orders.

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * If fails, `enableMultiTabIndexedDbPersistence()` will reject the promise or
nit: "enableMultiTabIndexedDbPersistence" -> "enableIndexedDbPersistence".

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * If fails, `enableMultiTabIndexedDbPersistence()` will reject the promise or
nit: "If fails" -> "On failure"

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * throw an error. There are several reasons why this can fail, which can be
nit: "throw an error" -> "throw an exception"

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * Note that even after this failure, the {@link Firestore} instance will remain
nit: "even after this failure" -> "even after a failure"

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * {@link clearIndexedDbPersistence}. Failing to do so will make this
I would omit the sentence beginning with "Failing to do so will..."

2023-12-19 03:09 UTC, dconeybe commented on packages/firestore/src/api/database.ts
> + * If fails, `enableMultiTabIndexedDbPersistence()` will reject the promise or
Please make the same changes to the docs for `enableMultiTabIndexedDbPersistence()` as are made to `enableIndexedDbPersistence()`.

2023-12-19 21:34 UTC, dconeybe approved these changes

2023-12-20 22:30 UTC, markarndt approved these changes

2023-12-21 15:05 UTC, merged