Allow user to set location
firebase/firebase-js-sdk pull request #8219
Opened 2024-05-03 22:13 UTC by hsubox76

Revert the location part of https://github.com/firebase/firebase-js-sdk/pull/8124 and allow user to set location again.

Also get rid of some TS errors on SafetyRatings in tests.

2024-05-04 00:11 UTC, DellaBitta requested changes

2024-05-04 00:11 UTC, DellaBitta commented on packages/vertexai/src/index.ts
> +        console.log(location);
Should this still be here?

2024-05-04 00:11 UTC, DellaBitta commented on packages/vertexai/src/service.test.ts
> +});
Nice to include both sides of the fence. :+1:

2024-05-06 15:47 UTC, dlarocque approved these changes
LGTM after @ DellaBitta's request changes

2024-05-06 17:16 UTC, hsubox76 commented on packages/vertexai/src/index.ts
> +        console.log(location);
Nope! Thanks.

2024-05-06 17:38 UTC, DellaBitta approved these changes

2024-05-06 18:20 UTC, merged