Implement solution to replace error messages with error codes, instead of removing error messages.
firebase/firebase-js-sdk pull request #8313
Opened 2024-06-12 17:42 UTC by MarkDuckworth

2024-06-12 19:25 UTC, dconeybe commented
IMO adding 2.4 kB to the bundle size is questionable if it's worth it.

2024-06-12 19:35 UTC, MarkDuckworth commented
> IMO adding 2.4 kB to the bundle size is questionable if it's worth it.

@dconeybe, it's <=1% increase for making production issues more debuggable. In your opinion, what increase in bundle size would be acceptable?

2024-06-12 20:34 UTC, dconeybe commented
> > IMO adding 2.4 kB to the bundle size is questionable if it's worth it.
> 
> @dconeybe, in your opinion, what increase in bundle size would be acceptable?
> 
> It's <=1% increase, which seems like a reasonable tradeoff for making production issues more debuggable. But I'm seeing if I can make the impact smaller.

I'd hope it would be less than 1kB. But this is just one man's opinion. Please don't take it as gospel truth.

2025-04-02 12:31 UTC, dconeybe approved these changes
This is fantastic! I especially like how you added the "context" which will be incredibly useful when debugging. Thanks for doing this, Mark.

2025-04-02 12:37 UTC, dconeybe commented
Please let the team know about the 1% increase in code bundle size and make sure they're ok with it. The "firestore (Read Write w Persistence)" bundle increased by 2.77 kB which is probably worth it, but I'd make sure the team knows.

Also, please add a change set with a minor version bump and a change log entry.

2025-04-03 13:22 UTC, dconeybe commented
FWIW I much prefer the "hashes" you had before over error codes numerically incrementing from zero. The reason is that hashes have much better "SEO" because of their uniqueness. Firstly, the improved SEO allows customers to search for the error code and find relevant bug reports, stack overflow posts, etc. If they search for error code "3" they won't likely get anything useful, but if they search for "jszxcbe37k" they'll likely get results that relate directly to the error that they are experiencing. Likewise, when we as Firestore SDK developers get a bug report with error code "3" it's much more difficult to find its place in the source code than searching for "jszxcbe37k".

For Data Connect I chose this alphabet: `[23456789abcdefghjkmnopqrstuvwxyz](https://github.com/firebase/firebase-android-sdk/blob/a0a02a73f67f6447c739d920f614c8bd5331c591/firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/AlphanumericStringUtil.kt#L31C45-L31C79)` (a length of 32). This alphabet is most of the English lowercase letters and most digits, with those that "look alike" removed (e.g. zero "0" and lowercase-o "o"). This leads to incredibly unique 6-digit strings.

2025-04-03 15:48 UTC, hsubox76 approved these changes

2025-04-08 16:36 UTC, dconeybe requested changes
Mostly LGTM. Just a few minor comments. Thanks for doing this work! I'll formally "approve" once the comments are addressed/refuted.

2025-04-08 16:36 UTC, dconeybe commented on .changeset/odd-wolves-sit.md
> +Add assertion IDs and optional context objects that will be included in production log statements for fail and hardAsserts
Consider a reword like this: Add unique IDs and state information into fatal error messages instead of the generic "unexpected state" message.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +    console.error(`Error reading directory ${dirPath}: ${error.message}`);
Consider simply letting the exception bubble up, possibly adding some contextual information. This error message could be easy to miss.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +        if (entry.name === 'node_modules') {
Consider using the `git check-ignore` command to exclude any files that are ignored by git, rather than hardcoding specific directories. If you like this idea, feel free to implement this in a follow-up PR.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
Consider using a third-party library like "fast-glob" (https://www.npmjs.com/package/fast-glob) rather than implementing your own bespoke recursive directory search algorithm. Feel free to do this in a follow-up PR, if desired.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +      console.error(`Error processing file ${filePath}: ${error.message}`);
Again, strongly consider just letting the exception bubble up and terminate the app. This "should" never fail, and if it does, IMO it should fail loudly.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +        ts.ScriptTarget.ESNext, // Or your project's target
What does this comment `// Or your project's target` mean? It sounds like copypasta :) Please remove it if it is not relevant, or reword it to suggest something actionable.

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +    process.exit(1);
Consider throwing an exception rather than calling process.exit().

2025-04-08 16:36 UTC, dconeybe commented on packages/firestore/scripts/assertion-id-tool.ts
> +main().catch(error => {
Can you just let the exception bubble up and crash the program?

2025-04-08 23:46 UTC, MarkDuckworth commented on .changeset/odd-wolves-sit.md
> +Add assertion IDs and optional context objects that will be included in production log statements for fail and hardAsserts
Updated. Thanks for the suggestion.

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
That's a good idea. I am going to save this for a future PR. I've hit the timebox for the current effort.

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +        if (entry.name === 'node_modules') {
That's clever. Definitely something to consider for a future PR...for the same reason

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +main().catch(error => {
yeah, implemented

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +    process.exit(1);
On this one I prefer `process.exit(1)`. The intent is for this to fail the build with a non-zero exit code. Throwing an error could make the failure appear as if there was an issue with the script, rather than an issue with the code it is checking.

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +      console.error(`Error processing file ${filePath}: ${error.message}`);
Good call. Removed the try catch.

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +        ts.ScriptTarget.ESNext, // Or your project's target
Good catch. Gemini used heavily to move this quickly. I removed this and a few other extraneous comments.

2025-04-08 23:46 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +    console.error(`Error reading directory ${dirPath}: ${error.message}`);
Good call. Logged and re-threw.

2025-04-08 23:47 UTC, MarkDuckworth commented on packages/firestore/scripts/assertion-id-tool.ts
> +        if (entry.name === 'node_modules') {
*reason == time boxing

2025-04-08 23:49 UTC, MarkDuckworth commented on packages/firestore/scripts/build-bundle.ts
Changes in this file are an artifact of running prettier on the scripts folder

2025-04-08 23:50 UTC, MarkDuckworth commented on packages/firestore/scripts/run-tests.ts
>  import { spawn } from 'child-process-promise';
Changes in this file are an artifact of running prettier on the scripts folder

2025-04-14 16:52 UTC, merged