Add reCAPTCHA Enterprise support for Phone Auth
firebase/firebase-js-sdk pull request #8568
Opened 2024-10-14 20:31 UTC by NhienLam

### Discussion

Currently, Firebase Auth Web SDK is relying on reCAPTCHA v2 to verify that the phone number verification request comes from one of the app's allowed domains to mitigate SMS abuse.

A downside of reCAPTCHA v2 is that end-users are required to solve a challenge. Therefore, we would like to give end-users a better user experience by integrating [reCAPTCHA Enterprise](https://cloud.google.com/recaptcha/docs/overview) with our phone auth flow. reCAPTCHA Enterprise is completely invisible to the user, so the phone auth flow will become seamless without user interaction.

### Testing

  * CI
  * Manual testing with test app

2024-10-15 22:25 UTC, Xiaoshouzi-gh approved these changes
LGTM

2024-10-16 20:51 UTC, hsubox76 approved these changes

2024-10-16 21:46 UTC, kevinthecheung requested changes

2024-10-16 21:46 UTC, kevinthecheung commented on packages/auth/src/platform_browser/providers/phone.ts
> +   * {@link ApplicationVerifier} is required in Audit mode but not in Enforce mode.
```suggestion
   * @param applicationVerifier - An {@link ApplicationVerifier}, which prevents
   * requests from unauthorized clients. This SDK includes an implementation
   * based on reCAPTCHA v2, {@link RecaptchaVerifier}. If you've enabled
   * reCAPTCHA Enterprise bot protection in Enforce mode, this parameter is
   * optional; in all other configurations, the parameter is required.
```

2024-10-16 21:46 UTC, kevinthecheung commented on packages/auth/src/platform_browser/strategies/phone.ts
> + * This SDK includes a reCAPTCHA-v2-based implementation, {@link RecaptchaVerifier}.
```suggestion
 * For abuse prevention, this method requires a {@link ApplicationVerifier}.
 * This SDK includes an implementation based on reCAPTCHA v2, {@link RecaptchaVerifier}.
```

2024-10-16 21:46 UTC, kevinthecheung commented on packages/auth/src/platform_browser/strategies/phone.ts
> + * mode but not in Enforce mode.
```suggestion
 * If you've enabled project-level reCAPTCHA Enterprise bot protection in
 * Enforce mode, you can omit the {@link ApplicationVerifier}.
```

2024-10-16 22:15 UTC, NhienLam commented on packages/auth/src/platform_browser/providers/phone.ts
> +   * {@link ApplicationVerifier} is required in Audit mode but not in Enforce mode.
Done.

2024-10-16 22:15 UTC, NhienLam commented on packages/auth/src/platform_browser/strategies/phone.ts
> + * This SDK includes a reCAPTCHA-v2-based implementation, {@link RecaptchaVerifier}.
Done.

2024-10-16 22:17 UTC, kevinthecheung approved these changes

2024-10-16 23:32 UTC, merged